### PR TITLE
Small corrections

### PR DESCRIPTION
**Pull request by antmendoza**
**Many thanks for submitting your Pull Request :heart:!**

**What this PR does / why we need it**:
requires  #56 to be merged 

**Special notes for reviewers**:

**Additional information (if needed):**

### CODE REVIEW

**Comment by tsurdilo** [comment]
@antmendoza should we exclude package-lock in gitignore? just wondering if that would be ok
needs rebase

**Review by tsurdilo — APPROVED** [review]

**Comment by tsurdilo** [comment]
@antmendoza ok after reading stuff around it it seems that we should not exclude package-lock, but use npm ci 
instead of npm install. i'm not an expert on this so not sure

**Comment by tsurdilo** [comment]
rebased for you :)

**Comment by antmendoza** [comment]
@tsurdilo I was about to write more or less the same

regarding to npm ci vs npm install, I though  that they have different propose. I am going to read around and come back to you.

**Pull request merged**
