### PR TITLE
update spec main branch

### PR DESCRIPTION
**Pull request by antmendoza**
**Many thanks for submitting your Pull Request :heart:!**

**What this PR does / why we need it**:
update spec main branch

**Special notes for reviewers**:

**Additional information (if needed):**

### CODE REVIEW

**Comment by antmendoza** [comment]
I just have seen that 0.8 spec has been released, will update this.

**Comment by tsurdilo** [comment]
@antmendoza yeah just created the tag a little earlier. let me know if i missed anything

**Comment by antmendoza** [comment]
ready @tsurdilo

**Review by tsurdilo — APPROVED** [review]

**Comment by tsurdilo** [comment]
@antmendoza thanks a lot! feel free to merge whenever you want

**Pull request merged**
