### PR TITLE
update to  v07 specification 

### PR DESCRIPTION
**Pull request by antmendoza**
**Many thanks for submitting your Pull Request :heart:!**

**What this PR does / why we need it**:

- updated to  v07 specification 
- changed url to fetch json schemas from github 

**Special notes for reviewers**:

**Additional information (if needed):**

### CODE REVIEW

**Comment by tsurdilo** [comment]
@antmendoza sorry i havent updated the schemas on website yet. will do today

**Review by tsurdilo — APPROVED** [review]

**Comment by tsurdilo** [comment]
@antmendoza updated - https://github.com/serverlessworkflow/serverlessworkflow.github.io/commit/5813b7ff616cc821097afe206650699217eabc53

**Comment by antmendoza** [comment]
> @antmendoza sorry i havent updated the schemas on website yet. will do today

thank you @tsurdilo,  I think that it is ok to pull the schemas from github as well

**Comment by tsurdilo** [comment]
> > @antmendoza sorry i havent updated the schemas on website yet. will do today
> 
> thank you @tsurdilo, I think that it is ok to pull the schemas from github as well

sounds good :) ty again for making these updates - you rock!

**Review by tsurdilo — APPROVED** [review]

**Review by JBBianchi — APPROVED** [review]
Great work, as usual ! 👍

**Pull request merged**
