### PR TITLE
Cross-platform build

### LINKED ISSUE #60: Support cross-platform build
**What would you like to be added**:
[shx](https://www.npmjs.com/package/shx) should be added to the dev dependencies and used to wrap the clean command

**Why is this needed**:
This would allow cross-platform build which is not possible at the moment on Windows because of the use of `rm`.

### PR DESCRIPTION
**Pull request by JBBianchi**
- added shx dev dependency, used to wrap clean command

Signed-off-by: JBBianchi <jb.bianchi@neuroglia.io>

**Many thanks for submitting your Pull Request :heart:!**

**What this PR does / why we need it**:
Wraps clean command with shx to provide cross-platform support
Closes #60

**Special notes for reviewers**:

**Additional information (if needed):**

### CODE REVIEW

**Review by antmendoza — APPROVED** [review]

**Comment by JBBianchi** [comment]
Hello @antmendoza, you're not doing anything wrong. I used `node node_modules/shx/lib/shx rm -rf dist` because I had binaries issues between my package installed from WSL & npm 7 and the actual execution in Windows & npm 6. But indeed, on a fresh install, it doesn't seem to work. 

I went back to the classic `shx rm -rf dist`, it should be working properly now.

Anyhow, I think using tsc might be a better alternative (#63) even if I seem to leave a blank folder architecture after the cleanup.

**Comment by antmendoza** [comment]
No idea about the error, I will have a look later today

**Comment by tsurdilo** [comment]
looks like some issue with the added workflow when running on 15.x (some auth issue). probably we should disable the 15.x runs for now ? you can do that here https://github.com/serverlessworkflow/sdk-typescript/blob/main/.github/workflows/node-ci.yml#L16

**Comment by tsurdilo** [comment]
@JBBianchi looks like the CI build cant deal w/ the added "shx". Is that absolutely required to have ?

**Comment by JBBianchi** [comment]
That's the point of this PR, using `shx` to use unix shell commands (`rm` in this case) on any os. It's not the only solution possible, we could use a js/ts script for the cleanup that rely on nodejs api instead of shell cmds but I must admit I don't really see the relation between `shx` and the auth error caused by npm 7 in the node 15 build.

**Comment by tsurdilo** [comment]
@JBBianchi yeah, I agree that we should not change our code to cater to some CI build but maybe there is another solution possible? wdyt?

**Comment by JBBianchi** [comment]
@tsurdilo the problem might come from the "corrupted" `package-lock.json` which contains links to Neuroglia private NPM registry/proxy. I'll fix this and see if it builds on node 15/npm 7.

**Comment by tsurdilo** [comment]
@JBBianchi haha nice catch I didnt even look at the diff for that :) yep that was it.

**Review by tsurdilo — APPROVED** [review]

**Comment by tsurdilo** [comment]
@JBBianchi @antmendoza whats a good way to prevent stuff like this to happen again in package-lock? Just wondering as we might get different contributors run into this issue

**Comment by JBBianchi** [comment]
@tsurdilo I don't know, maybe have a `.npmrc` that specifies the registry to use but it can still be overriden with a --registry flag ... 

I also noticed another problem, my dev environement still uses npm 6 which means the package-lock `lockfileVersion` will be set to `1` and the format will change if I npm install. I don't know if there is a way to enforce using npm 7 or if it might be a good idea to use another package manager like pnpm. I'll try to find some doc/pointers.

**Comment by antmendoza** [comment]
I think that one of the objectives of using  "npm ci" is to detect differences between package.json and package-lock.json https://docs.npmjs.com/cli/v7/commands/npm-ci , which is what has actually happened here. 

no idea why it has not failed with node 10,11,12... I am going to try to reproduce it in my env and see.

**Comment by JBBianchi** [comment]
The two main guidelines would be:

- enforce the use of a version of node/npm, add [engines.node and engines.npm](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines) to `package.json`
- enfore a project specific registry (and scoped ones if necessary), use a `.npmrc` to specify the registry

**Pull request merged**
